### ISSUE TITLE
Instructions for building without Docker

### ISSUE THREAD

**Issue by mortenfyhn** [oceanscan/ros-imc-broker#1]
Do you have instructions for how to build and set up this package without Docker? The Docker instructions work well, but I'm trying to build it in my regular environment.

**Comment by rasmartins** [comment]
Just follow the instructions in https://github.com/oceanscan/ros-imc-broker/blob/master/docker/Dockerfile

**Comment by mortenfyhn** [comment]
I did, but I have ROS installed and DUNE built already, in other locations than what the install assumes. I also have additional custom IMC messages on my system. I did however get it installed and running. The supplied `roslaunch` starts without error and `rostopic list` lists a number of `IMC/[...]` topics. However, `rostopic echo` fails with `ERROR: Cannot load message class for [<message>]. Are your messages built?` and `rosmsg show <message>` fails with `Unable to load msg [<message>]`. Any ideas?

**Comment by rasmartins** [comment]
This project uses builtin messages. Just take a look at https://github.com/oceanscan/ros-imc-broker/blob/master/workspace/src/ros_imc_broker/include/ros_imc_broker/ImcTypes.hpp

**Comment by mortenfyhn** [comment]
I did, and I updated ImcTypes.hpp with my full list of IMC messages using your script. But I think I'm missing something when building. Is it sufficient to simply have ImcTypes present?

**Comment by rasmartins** [comment]
Sorry but I do not understand the problem you're having. If you can compile ros-imc-broker then everything should be Ok. What issues are you having building the software ?

**Comment by mortenfyhn** [comment]
Running `catkin_make` works fine, but ROS does not seem to recognize the messages. As mentioned above, I get errors when I for instance run `rosmsg show <message>`. I have of course sourced devel/setup.bash.

**Comment by rasmartins** [comment]
And inside the docker container those commands show what you expect ? Which distribution are you using ?

**Comment by mortenfyhn** [comment]
That's a good point, I only checked that I could run the node in the Docker container. I'll check the message definitions inside it too and get back to you. I'm running kinetic.

**Comment by mortenfyhn** [comment]
The behaviour is the same in the container (cannot `rosmsg show` etc.). I think I may have misunderstood what this package does. Is what it does to allow sending IMC messages over ROS topics? Can you give me an example use case? What I'm trying to do is simply to translate incoming ROS messages to IMC messages to be sent to a DUNE system, so that they can communicate (only one-way for now).

**Comment by rasmartins** [comment]
This package does indeed allow you to send and receive IMC messages over TCP. The ros_imc_broker_node will connect to a TCP server (usually running DUNE) and will receive all published IMC messages and dispatch them to other ROS nodes using the appropriate topics. It will also listen to IMC topics from other ROS nodes and will publish them to the TCP server. Take a look at this simple controller https://github.com/oceanscan/ros-imc-broker/blob/master/workspace/src/ros_imc_broker/include/ros_imc_broker/SimpleController.hpp

**Comment by mortenfyhn** [comment]
Thank you, I did get it up and running. I had to add the `-pthread` compiler flag to make it build on my system.

**Comment by rasmartins** [comment]
Did you use the -pthread or -lpthread flag ? Where did you add it ? Which system are you using ?

**Comment by mortenfyhn** [comment]
I used -pthread: `set(CMAKE_CXX_FLAGS " -pthread ")` in CMakeLists. I'm not sure about the difference with -lpthread. Running ROS Kinetic on Mint 18.2.
