### ISSUE TITLE
Howto properly set DUNE_ROOT to use non-installed version of DUNE

### ISSUE THREAD

**Issue by krisklau** [oceanscan/ros-imc-broker#2]
Hi,

To get the broker up and running on my system without installing DUNE (but rather use the package in my dune build folder), i manually edited FindDUNE.cmake to explicitly search this path. 

There seems to be functionality in https://github.com/oceanscan/ros-imc-broker/blob/master/workspace/src/ros_imc_broker/cmake/FindDUNE.cmake#L26 to add a path using the variable DUNE_ROOT, but I was unable to make it work as intended. Among others, I tried adding a bash environment variable DUNE_ROOT. 

How is it supposed to be used? 

Best regards,
Kristian

**Comment by rasmartins** [comment]
There was an issue with the FindDUNE cmake script, please try my latest commit. Nevertheless you should point DUNE_ROOT to a folder where DUNE is installed. For example:

Sources: /home/someone/dune
Build folder: /home/someone/dune/build
Install folder (DUNE_ROOT): /home/someone/dune/build/install

Building DUNE with:

mkdir /home/someone/dune/build &&
cmake -G Ninja -DCMAKE_INSTALL_PREFIX=$PWD/install .. &&
ninja install

Will give you a proper DUNE_ROOT in /home/someone/dune/build/install, which you can use to build the broker with:

catkin_make -DDUNE_ROOT=/home/someone/dune/build/install

**Comment by krisklau** [comment]
Thank you @rasmartins, this worked perfectly :) 

On a different note, consider this a feature-suggestion: It would be very convenient if there was a catkin_make target that ran imc-translator.py if a source IMC xml file was set similarly to above.
