### ISSUE TITLE
ROS doesn't know where to find message definitions

### ISSUE THREAD

**Issue by miquelmassot** [oceanscan/ros-imc-broker#4]
When running in console:
`rostopic echo /IMC/In/EstimatedState`
ROS system replies
`ERROR: Cannot load message class for [imc/EstimatedState]. Are your messages built?`

This has something to do with message definitions being available to the whole workspace, and not only the package itself. If I were to publish a _imc/VehicleState_ message, it would mean that there should be a ROS package named _imc_ who builds a _VehicleState.msg_.

**Comment by miquelmassot** [comment]
I tried to fake it with a package _fake_imc_ https://github.com/miquelmassot/fake_imc and then MD5 checksums don't match. 
`[ERROR]: Client [/rostopic_7260_1509658822274] wants topic /IMC/In/EstimatedState to have datatype/md5sum [imc/EstimatedState/88de35f1d00f018632fd73d830af0e6c], but our version has [imc/EstimatedState/91d82bdfe6c4a5c936b87baac61a914b]. Dropping connection.
`
Is there any reason why your MD5 are there hardcoded?

**Comment by rasmartins** [comment]
Hi Miquel,

This project uses bultin messages as described in this document:

http://wiki.ros.org/roscpp/Overview/MessagesSerializationAndAdaptingTypes

The reason for this design choice is simple: ROS does not support message fields that are themselves other (polymorphic) messages and IMC uses this functionality profusely. Therefore since these messages are not defined in the ROS msg format the rostopic script cannot read their contents.

**Comment by miquelmassot** [comment]
Tried to use the builtin messages as you proposed in a simple package (https://github.com/srv/turbot_imc_broker) but the compilation claims there are no implementations for members: 
```
__getMD5Sum
__getDataType
__getMessageDefinition
```
I will paste somewhere the ouput of catkin_make.

**Comment by miquelmassot** [comment]
see it here: https://pastebin.com/MNieugaE

**Comment by rasmartins** [comment]
Hi Miquel,

As with any template the compiler must be able to see its definition. You must include the following in your sources:

#include <ros_imc_broker/ImcTypes.hpp>

Which in turns needs to see the headers:

#include <IMC/Base/Packet.hpp>
#include <IMC/Spec/AllMessages.hpp>

You need to add the ros-imc-broker folder src/ros_imc_broker/include/ to your CMake include_directories() list.

I hope this helps.

**Comment by miquelmassot** [comment]
Understood. Serialization for C++ is provided and works for any C++ node in ros. There is no introspection for messages or other non-C++ related tools such as _rostopic_ or _rqt_plot_. The example I tried in http://github.com/srv/turbot_imc_broker works and I can see the messages arriving to Neptus IMC console.

Thanks @rasmartins!
