### ISSUE TITLE
Working without Dune

### ISSUE THREAD

**Issue by miquelmassot** [oceanscan/ros-imc-broker#5]
Hi all,

First of all, thanks for providing this example, it is working for us using Dune and our software. However, from now on we would like to make it work without Dune. After speaking to LSTS, apparently, the TCP client should be replaced by a TCP server and a UDP broadcast multicast is also needed. I tried to work on it and I was wondering if anyone here could help, since I have no experience working with asio tcp/udp nor with IMC or Neptus. 

The version I have started is here: https://github.com/srv/ros-imc-broker/tree/feature/servers, which implements a ROS node offering these services, which I don't quite understand. 

Has anyone time to give it a look?

**Comment by paulosousadias** [comment]
This is being worked on https://github.com/paulosousadias/ros-imc-broker/tree/feature/vehicle-adapter.
